-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 16:24:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema competitions
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema competitions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music` DEFAULT CHARACTER SET utf8 ;
USE `music` ;

-- -----------------------------------------------------
-- Table `music`.`ALBUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music`.`ALBUM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NOT NULL,
  `artist` VARCHAR(250) NOT NULL,
  `release` INT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `music`.`SONG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music`.`SONG` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `album_id` INT NOT NULL,
  `title` VARCHAR(250) NOT NULL,
  `trackNum` INT,
  PRIMARY KEY (`id`),
  CONSTRAINT `s_album_id`
    FOREIGN KEY (`album_id`)
    REFERENCES `music_musicalbums`.`ALBUM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=1;
